Fix raw_cte_queryset in Subqueries
When a CTE is created with raw_cte_sql the query object,
raw_cte_queryset.query, does not implement resolve_expression, causing
an AttributeError. Specifically, this occurs when we use it within a
Subquery. This patch adds resolve_expression implementation to
raw_cte_queryset.query that simply returns cls. This satisfies django
ORM because of duck typing and since the query is raw SQL, no actual
expression resolution is needed.