License classifiers are deprecated
ConfigError: License classifiers are deprecated in favor of the license expression.
Remove the 'License :: OSI Approved :: BSD License' classifier